/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectRouteImport } from './routes/_project'
import { Route as ProjectIndexRouteImport } from './routes/_project/index'
import { Route as ProjectProjectsProjectIdRouteImport } from './routes/_project/projects.$projectId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectRoute = ProjectRouteImport.update({
  id: '/_project',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIndexRoute = ProjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectRoute,
} as any)
const ProjectProjectsProjectIdRoute =
  ProjectProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => ProjectRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProjectIndexRoute
  '/settings': typeof SettingsRoute
  '/projects/$projectId': typeof ProjectProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/settings': typeof SettingsRoute
  '/': typeof ProjectIndexRoute
  '/projects/$projectId': typeof ProjectProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_project': typeof ProjectRouteWithChildren
  '/settings': typeof SettingsRoute
  '/_project/': typeof ProjectIndexRoute
  '/_project/projects/$projectId': typeof ProjectProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to: '/settings' | '/' | '/projects/$projectId'
  id:
    | '__root__'
    | '/_project'
    | '/settings'
    | '/_project/'
    | '/_project/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProjectRoute: typeof ProjectRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_project': {
      id: '/_project'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_project/': {
      id: '/_project/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProjectIndexRouteImport
      parentRoute: typeof ProjectRoute
    }
    '/_project/projects/$projectId': {
      id: '/_project/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectProjectsProjectIdRouteImport
      parentRoute: typeof ProjectRoute
    }
  }
}

interface ProjectRouteChildren {
  ProjectIndexRoute: typeof ProjectIndexRoute
  ProjectProjectsProjectIdRoute: typeof ProjectProjectsProjectIdRoute
}

const ProjectRouteChildren: ProjectRouteChildren = {
  ProjectIndexRoute: ProjectIndexRoute,
  ProjectProjectsProjectIdRoute: ProjectProjectsProjectIdRoute,
}

const ProjectRouteWithChildren =
  ProjectRoute._addFileChildren(ProjectRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProjectRoute: ProjectRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
