/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as WorkspaceIndexRouteImport } from './routes/_workspace/index'
import { Route as WorkspaceWorkspacesWorkspaceIdRouteImport } from './routes/_workspace/workspaces.$workspaceId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceWorkspacesWorkspaceIdRoute =
  WorkspaceWorkspacesWorkspaceIdRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => WorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceIndexRoute
  '/settings': typeof SettingsRoute
  '/workspaces/$workspaceId': typeof WorkspaceWorkspacesWorkspaceIdRoute
}
export interface FileRoutesByTo {
  '/settings': typeof SettingsRoute
  '/': typeof WorkspaceIndexRoute
  '/workspaces/$workspaceId': typeof WorkspaceWorkspacesWorkspaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/settings': typeof SettingsRoute
  '/_workspace/': typeof WorkspaceIndexRoute
  '/_workspace/workspaces/$workspaceId': typeof WorkspaceWorkspacesWorkspaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/workspaces/$workspaceId'
  fileRoutesByTo: FileRoutesByTo
  to: '/settings' | '/' | '/workspaces/$workspaceId'
  id:
    | '__root__'
    | '/_workspace'
    | '/settings'
    | '/_workspace/'
    | '/_workspace/workspaces/$workspaceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/': {
      id: '/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/workspaces/$workspaceId': {
      id: '/_workspace/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkspaceWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceWorkspacesWorkspaceIdRoute: typeof WorkspaceWorkspacesWorkspaceIdRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceWorkspacesWorkspaceIdRoute: WorkspaceWorkspacesWorkspaceIdRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WorkspaceRoute: WorkspaceRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
